# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/Ps2_kb/Ps2_kb.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ps2_kb || ORIG_REF_NAME==Ps2_kb} -quiet] -quiet

# IP: bd/Ps2_kb/ip/Ps2_kb_vio_0_0/Ps2_kb_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ps2_kb_vio_0_0 || ORIG_REF_NAME==Ps2_kb_vio_0_0} -quiet] -quiet

# IP: bd/Ps2_kb/ip/Ps2_kb_ps2_keyboard_to_ascii_0_0/Ps2_kb_ps2_keyboard_to_ascii_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ps2_kb_ps2_keyboard_to_ascii_0_0 || ORIG_REF_NAME==Ps2_kb_ps2_keyboard_to_ascii_0_0} -quiet] -quiet

# XDC: d:/TK_HTN/PS2_keyboard/PS2_keyboard.gen/sources_1/bd/Ps2_kb/Ps2_kb_ooc.xdc
